[project]
name = "experiments-global-ensembles"
version = "0.1.0"
description = "Dynamic ensembles for global time series forecasting"
readme = "README.md"
authors = [
    { name = "Vitor Cerqueira", email = "cerqueira.vitormanuel@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "catboost",
    "datasets",
    "datasetsforecast",
    "matplotlib",
    "metaforecast==0.3.3",
    "neuralforecast==3.2.1",
    "numpy",
    "pandas",
    "python-dotenv",
    "scikit-learn",
    "seaborn",
    "statsforecast",
]

[build-system]
requires = ["setuptools>=68.0,<81"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
